#!/bin/bash

if [ "$(id -u)" == 0 ] ; then
   echo "Do not run this script as root"
   exit 1
fi

# Don't continue script if any error occurs.
set -e

echo
echo "                       .:          "
echo "               .:-:    :--.        "
echo "              :-----:. .----.      Welcome to nwg-shell, a GTK3-based user interface for sway and Hyprland Wayland compositors."
echo "      -:       .------::-----      "
echo "      ---:       .----------:      This script will prepare your system and install compositors, the shell and all dependencies."
echo "      -----:       .---------      This may take a while, as most packages come from the Arch User Repository and need to be built."
echo "      -------:.      .-------      Sit back and wait for the script to finish. Then restart the machine and you're ready to go."
echo "      ---------:.      .----:      "
echo "      -----------:.      .---      Copyright (c) 2022-2023 Piotr Miller & Contributors."
echo "      -----:.-------.      .:      All native shell components are distributed under the terms of the MIT License."
echo "      .:---.  .-----.              "
echo "         :-.    .:.                "
echo "          ..                       "
echo

sudo pacman -S --noconfirm git man-db vi xdg-user-dirs sddm

echo Initializing XDG user directories
xdg-user-dirs-update

echo "Adding $USER to video group"
sudo usermod -aG video $USER

echo "Enabling display manager"
sudo systemctl enable sddm.service

echo "Enabling NetworkManager"
sudo systemctl enable NetworkManager.service

echo
echo "You are about to select components, that need to be preinstalled for the key bindings to work."
echo "None of them is a shell dependency, and you're free to change them any time later."
echo

PS3="Select file manager: "
select fm in thunar caja dolphin nautilus nemo pcmanfm;
do
    break
done
echo

PS3="Select text editor: "
select editor in mousepad atom emacs gedit geany kate vim;
do
    break
done
echo

PS3="Select web browser: "
select browser in chromium brave-bin google-chrome epiphany falkon firefox konqueror microsoft-edge-stable-bin midori opera qutebrowser seamonkey surf vivaldi;
do
    break
done
echo

echo "Installing selection: $fm $editor $browser"
baph -inN $fm $editor $browser

echo Installing Simon Ser GPG key, needed by the wlr-randr AUR package
gpg --recv-key 0FDE7BE0E88F5E48

baph -inN hyprland wlr-randr

echo Installing nwg-shell
baph -inN nwg-shell

nwg-shell-installer -w -hypr
