#!/bin/bash

if [ "$(id -u)" == 0 ] ; then
   echo "Do not run this script as root"
   exit 1
fi

echo
echo "                        .        "
echo "               .,.     .d:.      "
echo "   .        .dddddddc. .dddddl     Welcome to nwg-shell, a GTK3-based user interface for sway and Hyprland Wayland compositors."
echo "   .        .dddddddc. .dddddl     "
echo "   d:.       .:dddddddc,dddddd.    This script will prepare your system and install compositors, the shell and all dependencies."
echo "   dddc.       .:ddddddddddddd.    This may take a while, as most packages come from the Arch User Repository and need to be built."
echo "   dddddc.       .:ddddddddddd.    Sit back and wait for the script to finish. Then restart the machine and you are ready to go."
echo "   dddddddc.       .:ddddddddd.    "
echo "   dddddddddc.       .:ddddddd.    "
echo "   dddddddddddc.       .:ddddd.    "
echo "   dddddddddddddl.        ;ddd.    Copyright (c) 2022-2023 Piotr Miller & Contributors."
echo "   dddddd,;dddddddl.        ,o.    All native shell components are distributed under the terms of the MIT License."
echo "   :ddddd.  ;ddddddd,              "
echo "    .:ddd.    ;ddd:.               "
echo "       ;o.      '.                 "

echo
echo "You are about to select components, that need to be preinstalled for the key bindings to work."
echo "None of them is a shell dependency, and you're free to change them any time later."
echo

PS3="Select file manager: "
select fm in thunar caja dolphin nautilus nemo pcmanfm;
do
    break
done
echo

PS3="Select text editor: "
select editor in mousepad atom emacs gedit geany kate vim;
do
    break
done
echo

PS3="Select web browser: "
select browser in chromium brave-bin google-chrome epiphany falkon firefox konqueror microsoft-edge-stable-bin midori opera qutebrowser seamonkey surf vivaldi;
do
    break
done
echo

echo "Adding $USER to video group"
sudo usermod -aG video $USER

echo Initializing XDG user directories
xdg-user-dirs-update

echo "Installing selection: $fm $editor $browser"
baph -inN $fm $editor $browser

echo "Installing CLI tools"
baph -inN fastfetch-bin pacseek-bin swayimg

baph -inN hyprland xdg-desktop-portal-hyprland

VIRT=$(systemd-detect-virt)

if [ "$VIRT" != "none" ]; then
    sudo sed -i '/^$/a export WLR_NO_HARDWARE_CURSORS=1' /etc/profile
fi

if [ "$VIRT" == "oracle" ]; then
    echo "Installing VirtualBox guest utils"
    baph -inN virtualbox-guest-utils ;
    sudo systemctl enable vboxservice.service
fi

# Iterate through all user directories
for user_dir in /home/*; do
    # Copy fastfetch config
    mkdir -p $user_dir/.config/fastfetch && cp /etc/nwg/fastfetch.config.jsonc $_/config.jsonc
    # Check if .bashrc file exists for the user
    if sudo test -f "$user_dir/.bashrc"; then
        # Remove the 'install-shell' string from .bashrc file using sed
        sudo sed -i '/install-shell/d' "$user_dir/.bashrc"
    fi
done

sed -i '$ a alias cls='\''clear'\''' ~/.bashrc
sed -i '$ a alias fetch='\''fastfetch'\''' ~/.bashrc
sed -i '$ a fastfetch' ~/.bashrc

echo Installing nwg-shell
baph -inN nwg-shell

echo "Enabling sddm display manager"
sudo systemctl enable sddm.service

nwg-shell-installer -w -hypr
